[build]
base = "project"
command = "npm run build:web"
publish = "project/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

If the app is at the repo root, use this:
[build]
command = "npm run build:web"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
