[build]
base = "project"
command = "npm ci --legacy-peer-deps && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22.12.0"
NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
