[build]
base = "project"
command = "npm ci --legacy-peer-deps && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18.20.8"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
